name: Deploy Website to EC2 
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "index.html"
          target: "/tmp/index.html"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Install Apache2 if not already installed
            if ! command -v apache2 &> /dev/null; then
              echo "Installing Apache2..."
              sudo apt update -y
              sudo apt install -y apache2
              sudo systemctl enable apache2
              sudo systemctl start apache2
            fi

            # Copy website file to Apache root
            sudo mv /tmp/index.html /var/www/html/index.html

            # Restart Apache
            sudo systemctl restart apache2

            echo "Website deployed successfully!"
